version: '2'

services:
  php:
    image: wodby/drupal:8-7.1-2.4.4
    environment:
      SSH_AUTH_SOCK: /ssh-agent/ssh-agent.sock
    volumes:
      - ~/.drush:/root/.drush
      - ssh-agent:/ssh-agent
    restart: always

  dns:
    image: puttydk/dnsmasq
    restart: always
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    cap_add:
      - NET_ADMIN
    command: --server=8.8.8.8 --address=/docker/127.0.0.1 --address=/localhost/127.0.0.1 --address=/loc/127.0.0.1

#volumes:
#  ssh-agent:
#    external: true
